import type { AppData, AppState } from "./types";

const now = "2026-04-24T00:00:00.000Z";

export const seedData: AppData = {
  skills: [
    {
      id: "skill-code-reviewer",
      slug: "code-reviewer",
      ownerRef: "skillhub-lab",
      defaultVariantRef: "variant-a",
      createdAt: now,
    },
    {
      id: "skill-research-summarizer",
      slug: "research-summarizer",
      ownerRef: "skillhub-lab",
      defaultVariantRef: "variant-research-default",
      createdAt: now,
    },
    {
      id: "skill-sql-migration",
      slug: "sql-migration-assistant",
      ownerRef: "skillhub-lab",
      defaultVariantRef: "variant-sql-default",
      createdAt: now,
    },
  ],
  tagSets: [
    { id: "tagset-codex", tagsHash: "codex", tags: ["codex"] },
    { id: "tagset-codex-gpt54", tagsHash: "codex|gpt5.4", tags: ["codex", "gpt5.4"] },
    { id: "tagset-opencode-minimax", tagsHash: "minimax2.7|opencode", tags: ["opencode", "minimax2.7"] },
  ],
  variants: [
    {
      id: "variant-a",
      skillRef: "skill-code-reviewer",
      name: "Variant A",
      label: "Codex baseline",
      summary: "通用 Codex 审查，关注 bug、测试缺口和可维护性。",
      tagSetRef: "tagset-codex",
      currentVersionRef: "version-a-v1",
      createdAt: now,
    },
    {
      id: "variant-b",
      skillRef: "skill-code-reviewer",
      name: "Variant B",
      label: "Codex + GPT-5.4 tuned",
      summary: "针对 GPT-5.4 的长上下文审查，引用更完整，但输出更长。",
      tagSetRef: "tagset-codex-gpt54",
      currentVersionRef: "version-b-v1",
      createdAt: now,
    },
  ],
  variantVersions: [
    {
      id: "version-a-v1",
      variantRef: "variant-a",
      version: "v1",
      contentRef: {
        kind: "inline_bundle",
        locator: "code-reviewer-a",
        digest: "sha-91aa",
      },
      changeNote: "初始 Codex 默认版本。",
      createdAt: now,
    },
    {
      id: "version-a-v0",
      variantRef: "variant-a",
      version: "v0",
      contentRef: {
        kind: "inline_bundle",
        locator: "code-reviewer-a-draft",
        digest: "sha-00aa",
      },
      changeNote: "早期草稿版本，输出噪声较多。",
      createdAt: "2026-04-20T00:00:00.000Z",
    },
    {
      id: "version-b-v1",
      variantRef: "variant-b",
      version: "v1",
      contentRef: {
        kind: "inline_bundle",
        locator: "code-reviewer-b",
        digest: "sha-23bc",
      },
      changeNote: "针对 GPT-5.4 的长上下文审查版本。",
      createdAt: now,
    },
  ],
  evalCorpora: [
    {
      id: "corpus-code-reviewer",
      skillRef: "skill-code-reviewer",
      createdAt: now,
    },
  ],
  evalCases: [
    {
      id: "case-null-check",
      corpusRef: "corpus-code-reviewer",
      title: "PR: 用户资料 nickname 变成可选字段",
      sourceType: "manual",
      inputArtifactRef: "artifact-input-null",
      expectationArtifactRef: "artifact-exp-null",
      graderRef: "grader-review-rubric-v1",
      expectation: "指出新增路径可能传入 null，并要求补测试。",
      createdAt: now,
    },
    {
      id: "case-race",
      corpusRef: "corpus-code-reviewer",
      title: "PR: 保存设置后异步刷新缓存",
      sourceType: "manual",
      inputArtifactRef: "artifact-input-race",
      expectationArtifactRef: "artifact-exp-race",
      graderRef: "grader-review-rubric-v1",
      expectation: "识别异步写入顺序不稳定，并说明可复现风险。",
      createdAt: now,
    },
    {
      id: "case-auth",
      corpusRef: "corpus-code-reviewer",
      title: "PR: 订单详情查询改为按 id 读取",
      sourceType: "manual",
      inputArtifactRef: "artifact-input-auth",
      expectationArtifactRef: "artifact-exp-auth",
      graderRef: "grader-review-rubric-v1",
      expectation: "指出缺少 owner 校验导致越权读取。",
      createdAt: now,
    },
    {
      id: "case-tests",
      corpusRef: "corpus-code-reviewer",
      title: "PR: CSV 导入错误处理改造",
      sourceType: "manual",
      inputArtifactRef: "artifact-input-tests",
      expectationArtifactRef: "artifact-exp-tests",
      graderRef: "grader-review-rubric-v1",
      expectation: "要求补充失败路径测试，而不是只看 happy path。",
      createdAt: now,
    },
    {
      id: "case-noise",
      corpusRef: "corpus-code-reviewer",
      title: "PR: 仅重命名局部变量",
      sourceType: "manual",
      inputArtifactRef: "artifact-input-noise",
      expectationArtifactRef: "artifact-exp-noise",
      graderRef: "grader-review-rubric-v1",
      expectation: "不要把低价值命名建议当成主要 finding。",
      createdAt: now,
    },
  ],
  evalCaseVersions: [],
  evalSetVersions: [
    {
      id: "evalset-v1",
      corpusRef: "corpus-code-reviewer",
      version: "v1",
      caseRefs: ["case-null-check", "case-race", "case-auth", "case-tests", "case-noise"],
      createdAt: now,
    },
  ],
  evalRuns: [
    {
      id: "run-a-v1",
      variantVersionRef: "version-a-v1",
      evalSetVersionRef: "evalset-v1",
      strategyRef: "manual-eval-v1",
      runConfigHash: "manual-v1",
      status: "finished",
      startedAt: now,
      finishedAt: now,
    },
    {
      id: "run-b-v1",
      variantVersionRef: "version-b-v1",
      evalSetVersionRef: "evalset-v1",
      strategyRef: "manual-eval-v1",
      runConfigHash: "manual-v1",
      status: "finished",
      startedAt: now,
      finishedAt: now,
    },
  ],
  caseResults: [
    { runRef: "run-a-v1", caseRef: "case-null-check", passed: true, score: 1 },
    { runRef: "run-a-v1", caseRef: "case-race", passed: true, score: 1 },
    { runRef: "run-a-v1", caseRef: "case-auth", passed: true, score: 1 },
    { runRef: "run-a-v1", caseRef: "case-tests", passed: true, score: 1 },
    { runRef: "run-a-v1", caseRef: "case-noise", passed: false, score: 0 },
    { runRef: "run-b-v1", caseRef: "case-null-check", passed: true, score: 1 },
    { runRef: "run-b-v1", caseRef: "case-race", passed: true, score: 1 },
    { runRef: "run-b-v1", caseRef: "case-auth", passed: false, score: 0 },
    { runRef: "run-b-v1", caseRef: "case-tests", passed: true, score: 1 },
    { runRef: "run-b-v1", caseRef: "case-noise", passed: true, score: 1 },
  ],
  sourceFeedback: [
    {
      id: "feedback-secret-log",
      skillRef: "skill-code-reviewer",
      variantVersionRef: "version-a-v1",
      tagSetRef: "tagset-codex",
      title: "JWT secret 被写入日志但审查未发现",
      failureType: "missed_security_issue",
      rawInput:
        'diff --git a/auth/session.ts b/auth/session.ts\n+ console.info("jwt secret", process.env.JWT_SECRET)\n+ return sign(payload, process.env.JWT_SECRET)',
      rawOutput:
        "Finding 1: 建议把 session.ts 中的变量名改得更清晰。\nFinding 2: 这里缺少针对 sign() 的单元测试。\n\n遗漏：没有指出 JWT_SECRET 被输出到日志。",
      createdAt: now,
    },
  ],
  artifacts: [
    {
      id: "artifact-input-null",
      kind: "eval_input",
      content:
        'diff --git a/profile.ts b/profile.ts\n- renderName(user.nickname.toUpperCase())\n+ renderName(user.nickname?.toUpperCase())\n+ saveDisplayName(user.nickname.toUpperCase())',
      contentHash: "hash-input-null",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-exp-null",
      kind: "expected_output",
      content: "审查结果应指出 saveDisplayName 仍然直接调用 user.nickname.toUpperCase()，nickname 可选时会崩溃，并建议补充空值测试。",
      contentHash: "hash-exp-null",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-input-race",
      kind: "eval_input",
      content:
        "diff --git a/settings.ts b/settings.ts\n+ await saveSettings(input)\n+ refreshCache(user.id)\n+ await publishSettingsChanged(user.id)",
      contentHash: "hash-input-race",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-exp-race",
      kind: "expected_output",
      content: "审查结果应指出 refreshCache 没有 await，后续事件可能在缓存刷新完成前发布，导致读到旧设置。",
      contentHash: "hash-exp-race",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-input-auth",
      kind: "eval_input",
      content:
        "diff --git a/orders.ts b/orders.ts\n- return db.order.findFirst({ where: { id, ownerId: viewer.id } })\n+ return db.order.findUnique({ where: { id } })",
      contentHash: "hash-input-auth",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-exp-auth",
      kind: "expected_output",
      content: "审查结果应指出 ownerId 过滤被移除，用户可能读取别人的订单，这是高风险越权问题。",
      contentHash: "hash-exp-auth",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-input-tests",
      kind: "eval_input",
      content:
        "diff --git a/importCsv.ts b/importCsv.ts\n+ if (!row.email.includes('@')) return { ok: false }\n+ return createUser(row)",
      contentHash: "hash-input-tests",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-exp-tests",
      kind: "expected_output",
      content: "审查结果应要求补充无效 email 的回归测试，并说明只覆盖 happy path 不足以验证导入失败路径。",
      contentHash: "hash-exp-tests",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-input-noise",
      kind: "eval_input",
      content:
        "diff --git a/price.ts b/price.ts\n- const value = calculateTotal(items)\n+ const total = calculateTotal(items)\n- return format(value)\n+ return format(total)",
      contentHash: "hash-input-noise",
      mediaType: "text/plain",
      createdAt: now,
    },
    {
      id: "artifact-exp-noise",
      kind: "expected_output",
      content: "审查结果不应把低价值命名建议当作主要 finding；如果没有实质风险，应保持简洁或说明无高价值问题。",
      contentHash: "hash-exp-noise",
      mediaType: "text/plain",
      createdAt: now,
    },
  ],
};

export function createInitialState(): AppState {
  return {
    view: "hub",
    selectedSkillRef: "skill-code-reviewer",
    requestedTags: ["codex"],
    evalSetVersionRef: "evalset-v1",
    selectedVariantRef: "variant-a",
    selectedVersionRef: "version-a-v1",
    data: structuredClone(seedData),
  };
}
