from __future__ import annotations

from .models import (
    AppData,
    Artifact,
    CaseResult,
    ContentRef,
    EvalCase,
    EvalCaseVersion,
    EvalCorpus,
    EvalRun,
    EvalSetVersion,
    Skill,
    TagSet,
    Variant,
    VariantVersion,
)


NOW = "2026-04-24T00:00:00.000Z"


def create_seed_data() -> AppData:
    return AppData(
        skills=[
            Skill(
                id="skill-code-reviewer",
                slug="code-reviewer",
                owner_ref="skillhub-lab",
                default_variant_ref="variant-a",
                created_at=NOW,
            )
        ],
        tag_sets=[
            TagSet(id="tagset-codex", tags_hash="codex", tags=["codex"]),
            TagSet(id="tagset-codex-gpt54", tags_hash="codex|gpt5.4", tags=["codex", "gpt5.4"]),
        ],
        variants=[
            Variant(
                id="variant-a",
                skill_ref="skill-code-reviewer",
                name="Variant A",
                label="Codex baseline",
                summary="通用 Codex 审查，关注 bug、测试缺口和可维护性。",
                tag_set_ref="tagset-codex",
                current_version_ref="version-a-v1",
                created_at=NOW,
            ),
            Variant(
                id="variant-b",
                skill_ref="skill-code-reviewer",
                name="Variant B",
                label="Codex + GPT-5.4 tuned",
                summary="针对 GPT-5.4 的长上下文审查，引用更完整，但输出更长。",
                tag_set_ref="tagset-codex-gpt54",
                current_version_ref="version-b-v1",
                created_at=NOW,
            ),
        ],
        variant_versions=[
            VariantVersion(
                id="version-a-v1",
                variant_ref="variant-a",
                version="v1",
                content_ref=ContentRef(kind="inline_bundle", locator="code-reviewer-a", digest="sha-91aa"),
                change_note="初始 Codex 默认版本。",
                created_at=NOW,
            ),
            VariantVersion(
                id="version-a-v0",
                variant_ref="variant-a",
                version="v0",
                content_ref=ContentRef(kind="inline_bundle", locator="code-reviewer-a-draft", digest="sha-00aa"),
                change_note="早期草稿版本，输出噪声较多。",
                created_at="2026-04-20T00:00:00.000Z",
            ),
            VariantVersion(
                id="version-b-v1",
                variant_ref="variant-b",
                version="v1",
                content_ref=ContentRef(kind="inline_bundle", locator="code-reviewer-b", digest="sha-23bc"),
                change_note="针对 GPT-5.4 的长上下文审查版本。",
                created_at=NOW,
            ),
        ],
        eval_corpora=[EvalCorpus(id="corpus-code-reviewer", skill_ref="skill-code-reviewer", created_at=NOW)],
        eval_cases=[
            EvalCase(
                id="case-null",
                corpus_ref="corpus-code-reviewer",
                title="PR: 用户资料 nickname 变成可选字段",
                source_type="manual",
                current_version_ref="casever-null-v1",
                created_at=NOW,
            ),
            EvalCase(
                id="case-auth",
                corpus_ref="corpus-code-reviewer",
                title="PR: 订单详情查询改为按 id 读取",
                source_type="manual",
                current_version_ref="casever-auth-v1",
                created_at=NOW,
            ),
            EvalCase(
                id="case-noise",
                corpus_ref="corpus-code-reviewer",
                title="PR: 仅重命名局部变量",
                source_type="manual",
                current_version_ref="casever-noise-v1",
                created_at=NOW,
            ),
        ],
        eval_case_versions=[
            EvalCaseVersion(
                id="casever-null-v1",
                case_ref="case-null",
                version="v1",
                input_artifact_ref="artifact-input-null",
                expectation_artifact_ref="artifact-exp-null",
                grader_ref="manual-pass-fail-v1",
                expectation="指出 nickname 可选时仍有直接调用 toUpperCase 的崩溃风险。",
                created_at=NOW,
            ),
            EvalCaseVersion(
                id="casever-auth-v1",
                case_ref="case-auth",
                version="v1",
                input_artifact_ref="artifact-input-auth",
                expectation_artifact_ref="artifact-exp-auth",
                grader_ref="manual-pass-fail-v1",
                expectation="指出 ownerId 过滤被移除，用户可能读取别人的订单。",
                created_at=NOW,
            ),
            EvalCaseVersion(
                id="casever-noise-v1",
                case_ref="case-noise",
                version="v1",
                input_artifact_ref="artifact-input-noise",
                expectation_artifact_ref="artifact-exp-noise",
                grader_ref="manual-pass-fail-v1",
                expectation="不要把低价值命名建议当作主要 finding。",
                created_at=NOW,
            ),
        ],
        eval_set_versions=[
            EvalSetVersion(
                id="evalset-v1",
                corpus_ref="corpus-code-reviewer",
                version="v1",
                case_version_refs=["casever-null-v1", "casever-auth-v1", "casever-noise-v1"],
                created_at=NOW,
            )
        ],
        eval_runs=[
            EvalRun(
                id="run-a-v1",
                variant_version_ref="version-a-v1",
                eval_set_version_ref="evalset-v1",
                strategy_ref="manual-eval-v1",
                run_config_hash="manual-v1",
                status="finished",
                started_at=NOW,
                finished_at=NOW,
            ),
            EvalRun(
                id="run-b-v1",
                variant_version_ref="version-b-v1",
                eval_set_version_ref="evalset-v1",
                strategy_ref="manual-eval-v1",
                run_config_hash="manual-v1",
                status="finished",
                started_at=NOW,
                finished_at=NOW,
            ),
        ],
        case_results=[
            CaseResult(run_ref="run-a-v1", case_version_ref="casever-null-v1", passed=True, score=1),
            CaseResult(run_ref="run-a-v1", case_version_ref="casever-auth-v1", passed=True, score=1),
            CaseResult(run_ref="run-a-v1", case_version_ref="casever-noise-v1", passed=False, score=0),
            CaseResult(run_ref="run-b-v1", case_version_ref="casever-null-v1", passed=True, score=1),
            CaseResult(run_ref="run-b-v1", case_version_ref="casever-auth-v1", passed=False, score=0),
            CaseResult(run_ref="run-b-v1", case_version_ref="casever-noise-v1", passed=True, score=1),
        ],
        artifacts=[
            Artifact(
                id="artifact-input-null",
                kind="eval_input",
                content="diff --git a/profile.ts b/profile.ts\n+ saveDisplayName(user.nickname.toUpperCase())",
                content_hash="hash-input-null",
                media_type="text/plain",
                created_at=NOW,
            ),
            Artifact(
                id="artifact-exp-null",
                kind="expected_output",
                content="应指出 nickname 可选时，saveDisplayName 仍然可能因 toUpperCase 崩溃。",
                content_hash="hash-exp-null",
                media_type="text/plain",
                created_at=NOW,
            ),
            Artifact(
                id="artifact-input-auth",
                kind="eval_input",
                content="diff --git a/orders.ts b/orders.ts\n- findFirst({ id, ownerId: viewer.id })\n+ findUnique({ id })",
                content_hash="hash-input-auth",
                media_type="text/plain",
                created_at=NOW,
            ),
            Artifact(
                id="artifact-exp-auth",
                kind="expected_output",
                content="应指出 ownerId 校验被移除，存在越权读取订单风险。",
                content_hash="hash-exp-auth",
                media_type="text/plain",
                created_at=NOW,
            ),
            Artifact(
                id="artifact-input-noise",
                kind="eval_input",
                content="diff --git a/price.ts b/price.ts\n- const value = calculateTotal(items)\n+ const total = calculateTotal(items)",
                content_hash="hash-input-noise",
                media_type="text/plain",
                created_at=NOW,
            ),
            Artifact(
                id="artifact-exp-noise",
                kind="expected_output",
                content="没有实质风险时应保持简洁，不要输出低价值命名 finding。",
                content_hash="hash-exp-noise",
                media_type="text/plain",
                created_at=NOW,
            ),
        ],
    )
