import type { EvalRunDetail, EvalSetVersionDetail, SkillDetail, SkillSummary } from "./types";

const now = "2026-05-05T10:00:00.000Z";

const artifacts = {
  skillBundle: {
    kind: "skill_bundle",
    locator: "memory:code-reviewer/codex",
    digest: "sha256-code-reviewer-codex-v2",
    path: "/skills/code-reviewer",
  },
  inputOwner: {
    id: "artifact-input-owner",
    kind: "eval_input",
    namespace: "skill-code-reviewer",
    locator: "inline:owner-check",
    digest: "sha256-owner-input",
    media_type: "text/plain",
    size_bytes: 1180,
    created_at: now,
    created_by: "skillhub-lab",
  },
  expectedOwner: {
    id: "artifact-expected-owner",
    kind: "expected_output",
    namespace: "skill-code-reviewer",
    locator: "inline:owner-expected",
    digest: "sha256-owner-expected",
    media_type: "text/plain",
    size_bytes: 220,
    created_at: now,
    created_by: "skillhub-lab",
  },
  inputNoise: {
    id: "artifact-input-noise",
    kind: "eval_input",
    namespace: "skill-code-reviewer",
    locator: "inline:rename-only",
    digest: "sha256-noise-input",
    media_type: "text/plain",
    size_bytes: 640,
    created_at: now,
    created_by: "skillhub-lab",
  },
  expectedNoise: {
    id: "artifact-expected-noise",
    kind: "expected_output",
    namespace: "skill-code-reviewer",
    locator: "inline:rename-expected",
    digest: "sha256-noise-expected",
    media_type: "text/plain",
    size_bytes: 190,
    created_at: now,
    created_by: "skillhub-lab",
  },
};

export const codeReviewerDetail: SkillDetail = {
  skill: {
    id: "skill-code-reviewer",
    slug: "code-reviewer",
    owner_ref: "skillhub-lab",
    default_variant_id: "variant-code-codex",
    lifecycle_status: "active",
    created_at: now,
    updated_at: now,
  },
  summary: {} as SkillSummary,
  variants: [
    {
      id: "variant-code-codex",
      skill_id: "skill-code-reviewer",
      name: "Variant A",
      label: "Codex baseline",
      summary: "通用代码审查 skill，重点输出 bug、回归风险和缺失测试。",
      tag_set_id: "tagset-codex",
      current_version_id: "version-code-codex-v2",
      lifecycle_status: "active",
      created_at: now,
      updated_at: now,
      tags: ["codex"],
      current_version: null,
      versions: [
        {
          id: "version-code-codex-v2",
          skill_id: "skill-code-reviewer",
          variant_id: "variant-code-codex",
          version_number: 2,
          content_ref: artifacts.skillBundle,
          content_digest: "sha256-code-reviewer-codex-v2",
          change_summary: "降低低价值命名建议的优先级，强化 owner check 和失败路径测试。",
          created_at: now,
          created_by: "maintainer",
        },
        {
          id: "version-code-codex-v1",
          skill_id: "skill-code-reviewer",
          variant_id: "variant-code-codex",
          version_number: 1,
          content_ref: {
            kind: "skill_bundle",
            locator: "memory:code-reviewer/codex-v1",
            digest: "sha256-code-reviewer-codex-v1",
          },
          content_digest: "sha256-code-reviewer-codex-v1",
          change_summary: "初始 Codex 默认版本。",
          created_at: "2026-04-28T10:00:00.000Z",
          created_by: "maintainer",
        },
      ],
    },
    {
      id: "variant-code-codex-gpt54",
      skill_id: "skill-code-reviewer",
      name: "Variant B",
      label: "Codex + GPT-5.4 tuned",
      summary: "偏长上下文审查，适合需要更完整引用和解释的环境。",
      tag_set_id: "tagset-codex-gpt54",
      current_version_id: "version-code-codex-gpt54-v1",
      lifecycle_status: "active",
      created_at: now,
      updated_at: now,
      tags: ["codex", "gpt5.4"],
      current_version: null,
      versions: [
        {
          id: "version-code-codex-gpt54-v1",
          skill_id: "skill-code-reviewer",
          variant_id: "variant-code-codex-gpt54",
          version_number: 1,
          content_ref: {
            kind: "skill_bundle",
            locator: "memory:code-reviewer/codex-gpt54",
            digest: "sha256-code-reviewer-codex-gpt54-v1",
          },
          content_digest: "sha256-code-reviewer-codex-gpt54-v1",
          change_summary: "针对长上下文输出调优。",
          created_at: now,
          created_by: "maintainer",
        },
      ],
    },
  ],
  eval_sets: [
    {
      id: "evalset-code-primary",
      skill_id: "skill-code-reviewer",
      name: "Primary",
      description: "核心回归测试集。",
      current_version_id: "evalsetver-code-v3",
      lifecycle_status: "active",
      created_at: now,
      updated_at: now,
      current_version: {
        id: "evalsetver-code-v3",
        skill_id: "skill-code-reviewer",
        eval_set_id: "evalset-code-primary",
        version_number: 3,
        created_at: now,
        created_by: "maintainer",
      },
      versions: [
        {
          id: "evalsetver-code-v3",
          skill_id: "skill-code-reviewer",
          eval_set_id: "evalset-code-primary",
          version_number: 3,
          created_at: now,
          created_by: "maintainer",
        },
        {
          id: "evalsetver-code-v2",
          skill_id: "skill-code-reviewer",
          eval_set_id: "evalset-code-primary",
          version_number: 2,
          created_at: "2026-04-30T10:00:00.000Z",
          created_by: "maintainer",
        },
      ],
    },
  ],
  latest_eval_runs: [
    {
      id: "evalrun-code-v2-primary",
      skill_id: "skill-code-reviewer",
      variant_version_id: "version-code-codex-v2",
      eval_set_version_id: "evalsetver-code-v3",
      strategy: "manual_pass_fail",
      status: "finished",
      summary: { passed: 5, failed: 1, total: 6 },
      result_artifact_id: null,
      created_at: now,
      created_by: "evaluator",
    },
  ],
  role_assignments: [
    {
      id: "role-code-owner",
      subject_type: "user",
      subject_id: "product-operator",
      resource_type: "skill",
      resource_id: "skill-code-reviewer",
      role: "owner",
      created_at: now,
      created_by: "system",
    },
  ],
  audit_events: [
    {
      id: "audit-code-owner",
      actor_ref: "product-operator",
      action: "role.assigned",
      resource_type: "skill",
      resource_id: "skill-code-reviewer",
      payload: { subject_id: "product-operator", role: "owner" },
      created_at: now,
    },
  ],
};

codeReviewerDetail.variants[0].current_version = codeReviewerDetail.variants[0].versions[0];
codeReviewerDetail.variants[1].current_version = codeReviewerDetail.variants[1].versions[0];
codeReviewerDetail.summary = {
  skill: codeReviewerDetail.skill,
  default_variant: codeReviewerDetail.variants[0],
  primary_eval_set: codeReviewerDetail.eval_sets[0],
  latest_accepted_eval_run: codeReviewerDetail.latest_eval_runs[0],
};

export const researchSummary: SkillSummary = {
  skill: {
    id: "skill-research-summarizer",
    slug: "research-summarizer",
    owner_ref: "skillhub-lab",
    default_variant_id: "variant-research-default",
    lifecycle_status: "active",
    created_at: now,
    updated_at: now,
  },
  default_variant: {
    id: "variant-research-default",
    skill_id: "skill-research-summarizer",
    name: "Variant A",
    label: "General research",
    summary: "把论文或网页材料压缩为带引用的研究摘要。",
    tag_set_id: "tagset-opencode-minimax",
    current_version_id: "version-research-v1",
    lifecycle_status: "active",
    created_at: now,
    updated_at: now,
    tags: ["opencode", "minimax2.7"],
    current_version: {
      id: "version-research-v1",
      skill_id: "skill-research-summarizer",
      variant_id: "variant-research-default",
      version_number: 1,
      content_ref: {
        kind: "skill_bundle",
        locator: "memory:research-summarizer/default",
        digest: "sha256-research-v1",
      },
      content_digest: "sha256-research-v1",
      change_summary: "初始研究摘要版本。",
      created_at: now,
      created_by: "maintainer",
    },
    versions: [],
  },
  primary_eval_set: null,
  latest_accepted_eval_run: null,
};

export const skillSummaries: SkillSummary[] = [codeReviewerDetail.summary, researchSummary];

export const evalSetVersionDetail: EvalSetVersionDetail = {
  eval_set_version: codeReviewerDetail.eval_sets[0].current_version!,
  eval_set: {
    id: "evalset-code-primary",
    skill_id: "skill-code-reviewer",
    name: "Primary",
    description: "核心回归测试集。",
    current_version_id: "evalsetver-code-v3",
    lifecycle_status: "active",
    created_at: now,
    updated_at: now,
  },
  cases: [
    {
      position: 0,
      case: {
        id: "case-owner-check",
        skill_id: "skill-code-reviewer",
        title: "PR: 订单详情查询缺少 owner 校验",
        current_version_id: "casever-owner-v2",
        lifecycle_status: "active",
        created_at: now,
        updated_at: now,
      },
      case_version: {
        id: "casever-owner-v2",
        skill_id: "skill-code-reviewer",
        case_id: "case-owner-check",
        version_number: 2,
        input_artifact_id: artifacts.inputOwner.id,
        expected_output_artifact_id: artifacts.expectedOwner.id,
        notes: "来自一次越权读取 missed finding。",
        created_at: now,
        created_by: "maintainer",
        input_artifact: artifacts.inputOwner,
        expected_output_artifact: artifacts.expectedOwner,
      },
    },
    {
      position: 1,
      case: {
        id: "case-rename-noise",
        skill_id: "skill-code-reviewer",
        title: "PR: 仅重命名局部变量",
        current_version_id: "casever-noise-v1",
        lifecycle_status: "active",
        created_at: now,
        updated_at: now,
      },
      case_version: {
        id: "casever-noise-v1",
        skill_id: "skill-code-reviewer",
        case_id: "case-rename-noise",
        version_number: 1,
        input_artifact_id: artifacts.inputNoise.id,
        expected_output_artifact_id: artifacts.expectedNoise.id,
        notes: "验证 skill 不应输出低价值 finding。",
        created_at: now,
        created_by: "maintainer",
        input_artifact: artifacts.inputNoise,
        expected_output_artifact: artifacts.expectedNoise,
      },
    },
  ],
};

export const evalRunDetail: EvalRunDetail = {
  eval_run: codeReviewerDetail.latest_eval_runs[0],
  skill: codeReviewerDetail.skill,
  variant_version: codeReviewerDetail.variants[0].versions[0],
  eval_set_version: codeReviewerDetail.eval_sets[0].current_version!,
  case_results: [
    {
      result: {
        run_id: "evalrun-code-v2-primary",
        skill_id: "skill-code-reviewer",
        case_version_id: "casever-owner-v2",
        passed: true,
        score: 1,
        result_artifact_id: null,
        created_at: now,
      },
      case: evalSetVersionDetail.cases[0].case,
      case_version: evalSetVersionDetail.cases[0].case_version,
    },
    {
      result: {
        run_id: "evalrun-code-v2-primary",
        skill_id: "skill-code-reviewer",
        case_version_id: "casever-noise-v1",
        passed: false,
        score: 0,
        result_artifact_id: null,
        created_at: now,
      },
      case: evalSetVersionDetail.cases[1].case,
      case_version: evalSetVersionDetail.cases[1].case_version,
    },
  ],
};
